### ISSUE TITLE
NPM Run Load Error: Model not found 

### ISSUE THREAD

**Issue by thymdi** [SAP-samples/cloud-cap-hana-swapi#5]
convertData.js file errors as model path '/gen/srv/srv/csn.json' doesn't exist

**Comment by jung-thomas** [comment]
Have you ran a `cds build` command first? That should create the /gen/ folder and output the csn model.

**Comment by thymdi** [comment]
I see the model path after cds build but with cds deploy --to hana the /gen/ folder is re-created and csn.json is moved to gen/db/last-dev.

Also, loading the data gives a load of errors of two types:
CompileMessage {
      message: 'CSN property ‘on’ can only be used alternatively to ‘keys’',
      location: [Object],
      '$location': [Object],
      validNames: null,
      severity: 'Error'

and

CompileMessage {
      message: 'CSN property ‘mixin’ is not expected in ‘projection’',
      location: [Object],
      '$location': [Object],
      validNames: null,
      severity: 'Error'

**Comment by jung-thomas** [comment]
>I see the model path after cds build but with cds deploy --to hana the /gen/ folder is re-created and csn.json is moved to gen/db/last-dev.

Interesting - it does that for me now as well. It seems like another cds build is needed after the cds deploy.  I'm not sure why the deploy is doing that though.  Perhaps a recent change to the way deploy works or a bug.  But it does seem like just running another cds build afterwards restores the full /gen folder. 

Although I don't receive any of the errors you reported when running the load script.  Here is my output when I ran it just now:
![image](https://user-images.githubusercontent.com/12159356/165952455-e3611857-7791-4273-81f0-7c57a27a120c.png)

Perhaps you can post a screenshot to get a sense of where those errors might be coming from. Also try running `cds version` from the same place you run the load script.  Maybe you are picking up an older, global install of CDS. Especially the mixin not expected in the projection sounds like maybe an older release.  I just tested against the latest available cds version. 
![image](https://user-images.githubusercontent.com/12159356/165952901-ae422121-d5d0-4fe0-a498-e231533183d1.png)

**Comment by thymdi** [comment]
When loaded the data using the restored /gen/ folder (after second build), got no errors.
Still getting the errors if I load with /gen/db/last-dev model.
The two generated csn.json files have some differences.

**Comment by jung-thomas** [comment]
Yes, I'm not sure why the srv content within /gen is getting wiped out by the deploy.  Seems to be not right to me.  But that csn in the /gen/db/last-dev is something different. It's how cds is just keep track of the changes that have been made to any part of the data model that uses persistence journaling/Schema Evolution.  https://github.com/SAP-samples/cloud-cap-hana-swapi/blob/96b5e0aabf5190a23fbe94718b7b215768c9c2dd/cap/db/schema.cds#L12  - this causes the creation of hdbmigrationtable instead of regular hdbtable. https://blogs.sap.com/2022/02/15/sap-cap-recent-enhancements-the-hana-dev-should-know-about/
But this isn't the complete model, it's only a partial model used internally within CAP to track changes.  

For the data load or any other usage of the CAP APIs you want the full model that should be in the /gen service folder.  So, the whole role problem here seems to be that /gen/srv is getting deleted for some reason when the cds deploy runs. But at least there is an easy work around to just run cds build again after a deploy to bring it back.

**Comment by thymdi** [comment]
Ok, I see. Thanks for explaining.

**Comment by jung-thomas** [comment]
I did add two notes to the README.md about this situation and I'll enter an internal ticket to try and see if we can figure out why the `/gen/srv` is getting cleared in the first place. 
Thanks,
Thomas Jung
